# Generated by Django 3.0.8 on 2020-08-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_art_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='art_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
